# Docker Compose for NekoLive Development and Production

version: '3.8'

services:
  # WebRTC Signaling Server
  nikolive-server:
    build: .
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - PORT=8080
      - ALLOWED_ORIGINS=https://your-domain.com,https://www.your-domain.com
      - RATE_LIMIT_REQUESTS=100
      - RATE_LIMIT_WINDOW_MS=60000
      - LOG_LEVEL=info
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - nikolive-network

  # Nginx Reverse Proxy (Production)
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
      - ./static:/usr/share/nginx/html:ro
    depends_on:
      - nikolive-server
    restart: unless-stopped
    networks:
      - nikolive-network

  # Redis for Session Storage (Optional - for scaling)
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    networks:
      - nikolive-network
    command: redis-server --appendonly yes

networks:
  nikolive-network:
    driver: bridge

volumes:
  redis-data:
